#!/bin/sh

# Tufan
addgroup --gid 102 lool
useradd lool --uid 101 -l -g lool -b /opt/lool -s /usr/sbin/nologin


# Refresh repos otherwise installations later may fail
apt-get update

# Install HTTPS transport
apt-get -y install apt-transport-https

# Install some more fonts
apt-get -y install fonts-open-sans

# Install gnupg2
apt-get -y install gnupg2

# install ca-certificates
apt-get -y install ca-certificates

# install ssh-keygen binary for the WOPI proof key
apt-get -y install openssh-client
apt-get -y install dirmngr

# Add Collabora repos
echo 'deb https://www.collaboraoffice.com/repos/CollaboraOnline/CODE-ubuntu2004 ./' >> /etc/apt/sources.list
apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 0C54D189F4BA284D
apt-get update

# Install the Collabora packages
apt-get update && apt-get install -y loolwsd code-brand collaboraofficebasis6.2-tr ollaboraoffice6.2-dict* 

# Install inotifywait and killall to automatic restart loolwsd, if loolwsd.xml changes
apt-get -y install inotify-tools psmisc

# Cleanup
#rm -rf /var/lib/apt/lists/*

# Remove WOPI Proof key generated by the package, we need unique key for each container
rm -rf /etc/loolwsd/proof_key*

# Fix permissions
chown -R lool:lool /opt/
chown -R lool:lool /etc/loolwsd
